### ISSUE TITLE
Unable to build assembly reference

### ISSUE THREAD

**Issue by laicasaane** [stride3d/stride#1028]
**Release Type**: Official Release

**Version**:
- Stride 4.0.1.1400
- .NET SDK 5.0.200
- Visual Studio 16.9.0

**Platform(s)**: Windows

**Describe the bug**

Unable to build assembly reference [F:\Projects\MyStrideGame\MyStrideGame\bin\Debug\netstandard2.0\MyStrideGame.dll]

```
[C:\Program Files\dotnet\sdk\5.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5)]: Error: The "ResolvePackageAssets" task failed unexpectedly.
System.MissingMethodException: Method not found: 'NuGet.ProjectModel.LockFileTarget NuGet.ProjectModel.LockFile.GetTarget(NuGet.Frameworks.NuGetFramework, System.String)'.
   at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTargetAndReturnNullIfNotFound(LockFile lockFile, String frameworkAlias, String runtimeIdentifier)
   at Microsoft.NET.Build.Tasks.LockFileExtensions.GetTargetAndThrowIfNotFound(LockFile lockFile, String frameworkAlias, String runtimeIdentifier)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

**To Reproduce**
1. Create new project
2. Observe output logs in the "Opening session" window

**Comment by KuraiAndras** [comment]
Same here

**Comment by xen2** [comment]
I think it should be fixed (in official release `4.0.1.1401`, github `master-4.0` and `master`)

**Comment by xen2** [comment]
Please reopen if you still have the issue.

**Comment by KuraiAndras** [comment]
it seems to work now

**Comment by rafftyl** [comment]
Still occuring on master (commit 34ed6faddf71cb5b67097445c9e810fab41011b4) when built from source.
Windows
Visual Studio 2019 16.9.2
.NET SDK 5.0.201
