### ISSUE TITLE
Using undo on an assembly reload causes various problems

### ISSUE THREAD

**Issue by adrsch** [stride3d/stride#2107]
**Release Type**: GitHub 

**Version**: Very recent

**Platform(s)**: Editor

**Describe the bug**
You can undo an assembly reload with ctrl+z, and it always causes problems.

I have had:
- Serialization errors requiring restart
- Actual crash of editor
- I want to say it causes a bug that's the bane of my existence, adding multiple copies of scripts, but I can't repro that right now so it may be something else. But I feel like this is what's causing it.

**To Reproduce**
1.  Get "assembly reload" as the top thing on the edit history panel
2. Press ctrl+z

**Expected behavior**
Personally I don't expect this to be something you can undo, and I never am doing this on purpose!

**Additional context**
I **_will_** submit a PR removing the ability to undo this unless anyone has other ideas to fix :laughing:

**Comment by adrsch** [comment]
I see in GameStudioAssemblyReloader, there are various operations pushed. Perhaps different things go wrong for each of the effects. But it still does have a near 100% repro rate, at least in my project, for causing problems.

**Comment by IXLLEGACYIXL** [comment]
can you reproduce it with this branch https://github.com/stride3d/stride/pull/2106 ?

**Comment by Kryptos-FR** [comment]
Please provide a MRE so that:
1. The issue can be investigated.
2. If confirmed as a bug, resolution can be discussed
3. Once a fix is implemented, the same MRE can be used to validate it.

**Comment by adrsch** [comment]
> can you reproduce it with this branch #2106 ?
> 
> i was able to unload properly

Very cool change! I will test that as soon as I can

**Comment by IXLLEGACYIXL** [comment]
> > Please provide a MRE so that:
> > 
> > 1. The issue can be investigated.
> > 2. If confirmed as a bug, resolution can be discussed
> > 3. Once a fix is implemented, the same MRE can be used to validate it.
> 
> I am unfamiliar with the terminology MRE. I will type up a reproduction using a sample project and a standard release, since I just came up with one.
> 
> Release 4.2.0.2067
> 
>     1. Create a new project using the "TopDownRPG" sample.
> 
>     2. Open MainScene in the editor
> 
>     3. Select the first LootBox prefab with the CrateScript component attached. Move this to a different position using the editor.
> 
>     4. Open the code project, and open CrateScript.cs
> 
>     5. Introduce a bug in this class preventing it from compiling.
> 
>     6. Go back to the editor, and reload scripts. It will fail to compile due to the error.
> 
>     7. Go back and remove the typo, making the class the same as it was when the project was first made.
> 
>     8. In the editor, reload script assemblies. This time, it will successfully compile.
> 
>     9. Press ctrl+z repeatedly and watch things break.
> 
> 
> Effects of this:
> 
>     * A second copy of CrateScript is present on the object (the instructions are exact, so the object has been selected the entire time, and you can see this immediately)
> 
>     * The Trigger script also has a second copy.
> 
>     * A `System.INvalidOperationException: Cannot convert value to the required type` prevents the scene from rendering
> 
>     * The move is not successfully undone, the object is still in the modified position after undo is pressed many times.
> 
> 
> Pressing "Resume" does successfully rescue the editor.
> 
> As the reload is undone, you are able to press the "Reload script assemblies" button again. You can press it and get a third copy of the CrateScript and Trigger script on the still

try out my PR as it fixes some parts of failed compilations too

**Comment by IXLLEGACYIXL** [comment]
as the undo works when jumping back to a succesful compilation, woudlnt it be better to skip undos that contain an invalid compilation than removing the undo entirely

**Comment by adrsch** [comment]
> can you reproduce it with this branch #2106 ?
> 
> i was able to unload properly



> as the undo works when jumping back to a succesful compilation, woudlnt it be better to skip undos that contain an invalid compilation than removing the undo entirely

That sounds a lot better actually

Also, going back to the branch I have your changes merged into, I think you did fix the serialization errors after running the procedure. It is just the duplicate scripts that I still get.

**Comment by IXLLEGACYIXL** [comment]
> > can you reproduce it with this branch #2106 ?
> > i was able to unload properly
> 
> > as the undo works when jumping back to a succesful compilation, woudlnt it be better to skip undos that contain an invalid compilation than removing the undo entirely
> 
> That sounds a lot better actually
> 
> Also, going back to the branch I have your changes merged into, I think you did fix the serialization errors after running the procedure. It is just the duplicate scripts that I still get. Either that or I'm getting lucky with testing in my main project for once.

then atleast 1 bug of the 2 is fixed :D

**Comment by adrsch** [comment]
> > > can you reproduce it with this branch #2106 ?
> > > i was able to unload properly
> > 
> > 
> > > as the undo works when jumping back to a succesful compilation, woudlnt it be better to skip undos that contain an invalid compilation than removing the undo entirely
> > 
> > 
> > That sounds a lot better actually
> > Also, going back to the branch I have your changes merged into, I think you did fix the serialization errors after running the procedure. It is just the duplicate scripts that I still get. Either that or I'm getting lucky with testing in my main project for once.
> 
> then atleast 1 bug of the 2 is fixed :D

Make that 1 of 3, or 2 of 3, since I was never able to consistently reproduce crashing xD I'll keep using your code since I got it merged in the branch I use. Crashing and the duplicate scripts are the 2 serious problems imo.

**Comment by IXLLEGACYIXL** [comment]
> > > > can you reproduce it with this branch #2106 ?
> > > > i was able to unload properly
> > > 
> > > 
> > > > as the undo works when jumping back to a succesful compilation, woudlnt it be better to skip undos that contain an invalid compilation than removing the undo entirely
> > > 
> > > 
> > > That sounds a lot better actually
> > > Also, going back to the branch I have your changes merged into, I think you did fix the serialization errors after running the procedure. It is just the duplicate scripts that I still get. Either that or I'm getting lucky with testing in my main project for once.
> > 
> > 
> > then atleast 1 bug of the 2 is fixed :D
> 
> Make that 1 of 3, or 2 of 3, since I was never able to consistently reproduce crashing xD I'll keep using your code since I got it merged in the branch I use. Crashing and the duplicate scripts are the 2 serious problems imo.

```
        private async Task ReloadAssemblies()
        {
            trackAssemblyChanges = false;

            var modifiedAssembliesCopy = new Dictionary<PackageLoadedAssembly, ModifiedAssembly>(modifiedAssemblies);
            var assembliesToReload = new List<ModifiedAssembly>();
            modifiedAssemblies.Clear();

            foreach (var assembly in assembliesToReload)
            {
                var compilation = await assembly.Project.GetCompilationAsync();
                if (compilation.GetDiagnostics().Any(x => x.Severity == DiagnosticSeverity.Error))
                {
                    return;
                }
            }
```
can you try this in the debugginviewmodel? can you reproduce the error this way?

**Comment by adrsch** [comment]
> > > > > can you reproduce it with this branch #2106 ?
> > > > > i was able to unload properly
> > > > 
> > > > 
> > > > > as the undo works when jumping back to a succesful compilation, woudlnt it be better to skip undos that contain an invalid compilation than removing the undo entirely
> > > > 
> > > > 
> > > > That sounds a lot better actually
> > > > Also, going back to the branch I have your changes merged into, I think you did fix the serialization errors after running the procedure. It is just the duplicate scripts that I still get. Either that or I'm getting lucky with testing in my main project for once.
> > > 
> > > 
> > > then atleast 1 bug of the 2 is fixed :D
> > 
> > 
> > Make that 1 of 3, or 2 of 3, since I was never able to consistently reproduce crashing xD I'll keep using your code since I got it merged in the branch I use. Crashing and the duplicate scripts are the 2 serious problems imo.
> 
> ```
>         private async Task ReloadAssemblies()
>         {
>             trackAssemblyChanges = false;
> 
>             var modifiedAssembliesCopy = new Dictionary<PackageLoadedAssembly, ModifiedAssembly>(modifiedAssemblies);
>             var assembliesToReload = new List<ModifiedAssembly>();
>             foreach (var assembly in assembliesToReload)
>             {
>                 var compilation = await assembly.Project.GetCompilationAsync();
>                 if (compilation.GetDiagnostics().Any(x => x.Severity == DiagnosticSeverity.Error))
>                 {
>                     return;
>                 }
>             }
>             modifiedAssemblies.Clear();
> ```
> 
> can you try this in the debugginviewmodel? can you reproduce the error this way? just fiddling a little bit around

Doesn't fix. I will update repro, I got the error to occur by making a valid change and using undo. Also I am getting the serialization error, even with your stuff, but, it is a different error than the other, this time, No serializer Available for type mytype. And it only happens with the original and duplicate copy present, and after the loading assets has gone on for a few seconds.

**Comment by IXLLEGACYIXL** [comment]
serializer not being available is caused by faulty loaded assemblys, which mine corrects FOR new compilations

**Comment by adrsch** [comment]
I got serious info - it's specifically because the scripts, in the repro step and what I'm looking at, are on prefabs and they are getting processed twice. This is by splitting up push operations into separate transactions. 

The problem operation is in GameStudioAssemblyReloader.ClearNode. This gives you tons of operations, for every object. 

Copy 1 appears undoing operation name "Unload object {myclass} in asset {my scene}".
Copy 2 appears undoing operation name "Unload object {myclass} in asset {my prefab}".

So it's getting processed twice.
